name: tencent_ad_example
description: 欢迎指正
publish_to: 'https://pub.dev/packages/tencent_ad' 
version: 1.0.4

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  tencent_ad:
    path: ../
  flutter_svg: ^0.18.0
  url_launcher: ^5.5.0
  fluttertoast: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  
  assets:
    - assets/svg/
