name: tencent_ad
description: 腾讯广告插件
version: 1.0.0
homepage: https://github.com/Mr-Cai/tencent_ad
environment:
  sdk: ">=2.6.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  plugin:
    platforms:
      android:
        package: tencent.ad
        pluginClass: TencentAD
      ios:
        pluginClass: TencentAD
        
  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
