name: tencent_ad
description: "腾讯广告优量汇插件(tencent_ad)是帮助中国大陆开发者使用Flutter
开发App时，方便实现广告盈利的。腾讯优量汇广告官方并未提供Flutter相关插件，
仅提供原生App接入文档，所以这里属于个人开发的插件。本插件提供了广告SDK的桥梁。
欢迎指正，共同进步。"

version: 1.0.2
homepage: https://github.com/Mr-Cai/tencent_ad

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tencent.ad
        pluginClass: TencentADPlugin
      ios:
        pluginClass: TencentADPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
