name: tencent_ad
description: "The plugin is bridge of the official SDK,
allowing Chinese developers to make money"

version: 1.0.2+3
homepage: https://github.com/Mr-Cai/tencent_ad

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: tencent.ad
        pluginClass: TencentADPlugin
      ios:
        pluginClass: TencentADPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
